server:
  port: 8086

spring:
  application:
    name: notification-service

  # ?? Base de donn�es ?????????????????????????????????????????????
  datasource:
    url: jdbc:mysql://localhost:3306/wifak_notification?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # ?? Email (SMTP) ????????????????????????????????????????????????
  mail:
    host: smtp.gmail.com       # Remplacer par votre SMTP (ex: smtp.office365.com)
    port: 587
    username: rawene.labaoui@gmail.com # Variable d'environnement
    password: vjjt srre beng aium  # Variable d'environnement (App Password Gmail)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

  # ?? Thymeleaf (templates HTML emails) ???????????????????????????
  thymeleaf:
    prefix: classpath:/templates/email/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0
    openfeign:
      httpclient:
        hc5:
          enabled: true

# ?? Eureka ??????????????????????????????????????????????????????
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: notification-service:8086
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    inetutils:
      preferred-networks:
        - 172.

eureka:
  instance:
    prefer-ip-address: true
    instance-id: notification-service:8086
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

keycloak:
  auth-server-url: http://keycloak:8080

# ?? Keycloak Admin ???????????????????????????????????????????????

keycloak:
  auth-server-url: http://localhost:8081
  realm: bct-realm
  admin-username: admin
  admin-password: rawene
  admin-client-id: admin-cli        # ? changer bct-backend ? admin-cli
  admin-client-secret:
# ?? S�curit� inter-services ??????????????????????????????????????
app:
  internal-secret: ${INTERNAL_SECRET:wifak-internal-secret-2024}
  cors:
    allowed-origins: http://localhost:4200

# ?? Logging ?????????????????????????????????????????????????????
logging:
  level:
    com.wifak.notificationservice: INFO
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"