server:
  port: 8085

spring:
  application:
    name: jira-integration-service

  datasource:
    url: jdbc:mysql://localhost:3306/wifak_jira?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/bct-realm
          jwk-set-uri: http://localhost:8081/realms/bct-realm/protocol/openid-connect/certs

  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0
    openfeign:
      httpclient:
        hc5:
          enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: jira-integration-service:8085
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

jira:
  base-url: https://wifak-bct.atlassian.net
  project-key: BCT
  user-email: rawene.labaoui@gmail.com
  api-token: ATATT3xFfGF0UVSZvQVI2t9HROjHGkcwd4v_fwaRn-COM9ARnLL_yuskLYajF4Ah68fi5XEGzGsc7ZetuWkynScY3b4e1gyS5S9yAU1-GNIUQM2pINPUup7csQgycgvCoeXS_JvD_TAywtK2m5LoqEs21dIsvaS0gjMyioadlEo9P7qSS0XNHCY=F664B0C6
  transitions:
    to-do: "10001"
    in-progress: "10002"
    validee: "10003"
    rejetee: "10004"
    envoyee: "2"

feign:
  client:
    config:
      bct-backend:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      validation-service:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic

app:
  cors:
    allowed-origins: http://localhost:4200
  internal-secret: ${INTERNAL_SECRET:wifak-internal-secret-2024}

logging:
  level:
    com.wifak.jiraintegration: INFO
    org.springframework.security: DEBUG
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: jira-integration-service

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    inetutils:
      preferred-networks:
        - 172.

eureka:
  instance:
    prefer-ip-address: true
    instance-id: jira-integration-service:8085
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
