sonar.projectKey=RawenLb_Projet-Wifak-PFE
sonar.organization=rawenlb
sonar.projectName=Projet Wifak PFE
sonar.projectVersion=1.0.0

# Sources
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/target/**,**/*.spec.ts,**/test/**

# Java modules
sonar.modules=Authentification,workflow-declaration

# Authentification module
Authentification.sonar.projectName=Authentification Service
Authentification.sonar.sources=src/main/java
Authentification.sonar.tests=src/test/java
Authentification.sonar.java.binaries=target/classes
Authentification.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Workflow-declaration module
workflow-declaration.sonar.projectName=Workflow Declaration Service
workflow-declaration.sonar.sources=src/main/java
workflow-declaration.sonar.tests=src/test/java
workflow-declaration.sonar.java.binaries=target/classes
workflow-declaration.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Frontend Angular
sonar.javascript.lcov.reportPaths=bct-frontend/coverage/bct-frontend/lcov.info
sonar.typescript.lcov.reportPaths=bct-frontend/coverage/bct-frontend/lcov.info
