apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: wifak-prod
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: wifak-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wifak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL
              value: "jdbc:mysql://mysql-service:3306/keycloak?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: KC_DB_USERNAME
              value: "root"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wifak-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_URL
              value: "http://bct.wifak.tn/auth"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "http://bct.wifak.tn/auth"
          volumeMounts:
            - name: keycloak-realm
              mountPath: /opt/keycloak/data/import
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm-config
