---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wifak
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: wifak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: wifak
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: wifak
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8088
      targetPort: 8088
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: authentification-service
  namespace: wifak
spec:
  selector:
    app: authentification-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: wifak
spec:
  selector:
    app: chat-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-declaration
  namespace: wifak
spec:
  selector:
    app: workflow-declaration
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: wifak
spec:
  selector:
    app: notification-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jira-integration-service
  namespace: wifak
spec:
  selector:
    app: jira-integration-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: wifak
spec:
  selector:
    app: ml-service
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wifak
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: wifak
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: wifak
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
